THREESCALE-11526 - Redis Sentinel with TLS for Porta and Backend
3scale/3scale-operator pull request #1041
Opened 2024-12-05 16:02 UTC by valerymo

Jira: https://issues.redhat.com/browse/THREESCALE-11526

New document that  provides an overview of Redis Sentinel with TLS, detailing the installation and configuration process (without using a Helm Chart).

2025-01-09 12:17 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +*We will use term **Sentinel** instead of full name **Sentinel** in most places in this doc.*
Redis Sentinel perhaps?

2025-01-09 12:19 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +The Guide includes not only Sentinel TLS configuration, but Redis server also, to be useful for Testing.
```suggestion
The guide includes both Sentinel TLS configuration and Redis server, which are useful for testing. 
```

2025-01-09 12:43 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +        image: redis:7
lets move out of dockerhub - mirror.gcr.io/library/redis:7

2025-01-09 12:43 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +        #image: quay.io/fedora/redis-6
can be removed?

2025-01-09 12:47 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +    #sentinel monitor mymaster redis.3scale-test.svc.cluster.local 6380 2
might be worth to explain that this is using the DNS instead and is recommended. My ns is different so maybe something like "sentinel monitor mymaster redis.<NAMESPACE>.svc.cluster.local 6380 2"

2025-01-09 12:50 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +          image: redis:7
mirror.gcr.io/library/redis:7 and I think I would remove the above comment

2025-01-09 12:50 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +            - containerPort: 26379
In above cm we only have tls-port 26380 - do we need 26379 as well here?

2025-01-09 12:58 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +    #sentinel monitor mymaster redis.3scale-test.svc.cluster.local 6380 2
I've tried it with dns and it failed.

2025-01-09 13:01 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +- We are providing only logs here. For installation details of Redis+Sentinel on EC2 - please see AWS and Redis docs or ChatGPT.
```suggestion
- We are providing only logs here. For installation details of Redis+Sentinel on EC2 - please see AWS and Redis docs.
```

2025-01-09 13:07 UTC, MStokluska commented on doc/redis-sentinel-tls.md
> +openssl req -new -key redis-sentinel.key -out redis-sentinel.csr -subj "/CN=redis-sentinel.3scale-test.svc.cluster.local"
^^ that comment makes no sense lol.
Basically, whenever we are mentioning DNS, maybe it would be better to expose DNS as part of your setup to run these commands and just use that instead? It's easy to miss it when doing for the first time

2025-01-09 13:08 UTC, MStokluska requested changes
Really nice doc @valerymo - well done! 
Couple of minor points etc, the only thing that would be really nice to solve here is the DNS sentinels instead of IP, with DNS it did not work for me.

2025-01-12 14:28 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +The Guide includes not only Sentinel TLS configuration, but Redis server also, to be useful for Testing.
Thank you for suggestion. Yes, need change it. I  actually wanted to say before - that the Guide is for Sentinel. But there is No Sentinel without Redis server, so providing Redis-server configuration also. So after "consulting" with ChatGPT  I changed it to "The guide includes both Sentinel TLS configuration and Redis server setup, which is necessary for testing Sentinel. "   Hope it looks better now.

2025-01-12 14:29 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +*We will use term **Sentinel** instead of full name **Sentinel** in most places in this doc.*
Thank you. Done.

2025-01-12 15:04 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +**Note**: To correctly generate the Redis server and Sentinel certificates, you need to use their services IPs as the Common Names (CN) in the certificates. If you haven’t set up the services yet, pl
Updated. Thank you

2025-01-12 15:28 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +- `redis-client.crt` and `redis-client.key`: The Redis client's certificate and key
Updated/added:
+- Other (intermediate) files, such as *.csr and ca.srl, are also generated. If needed, additional information can be found in the OpenSSL documentation.
Thank you

2025-01-12 16:19 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +        #image: quay.io/fedora/redis-6
Done. Thank you

2025-01-12 16:21 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +          image: redis:7
done. Thank you

2025-01-12 17:20 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +            - containerPort: 26379
non-TLS port can be useful for debugging in Testing environment. 
Thank you

2025-01-12 18:10 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +- We are providing only logs here. For installation details of Redis+Sentinel on EC2 - please see AWS and Redis docs or ChatGPT.
updated. Thank you

2025-01-12 18:13 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +    #sentinel monitor mymaster redis.3scale-test.svc.cluster.local 6380 2
I tried more but didn't succed to work with DNS for master monitoring . 
New section added : 
![image](https://github.com/user-attachments/assets/dfe6fa8b-a0b8-49ed-9b3a-7cb38013e68b)

2025-01-12 18:23 UTC, valerymo commented on doc/redis-sentinel-tls.md
> +openssl req -new -key redis-sentinel.key -out redis-sentinel.csr -subj "/CN=redis-sentinel.3scale-test.svc.cluster.local"
yes, meanwhile DNS is not working for master monitorying by Sentinel, so using IP.  "issues found" section added (see before). Thank you.

2025-01-12 18:29 UTC, valerymo commented
@MStokluska  Thank you for the review! I believe I have addressed all comments, and the changes are made in a separate commit. Regarding the DNS issue with master monitoring by Sentinel, I tried more, but without success, so will continue using the IP for now. A new section titled 'Issues Found' has been added to the documentation, explaining the problem. 
Thanks

2025-01-14 11:43 UTC, MStokluska approved these changes

2025-01-14 16:02 UTC, merged