[WIP]THREESCALE-11281 - bump to go 1.22
3scale/3scale-operator pull request #1045
Opened 2024-12-17 07:30 UTC by valerymo

Jira: https://issues.redhat.com/browse/THREESCALE-11281

## WIP
Try not change operator-sdk.   We want recheck PR https://github.com/3scale/3scale-operator/pull/1036

2025-01-08 10:36 UTC, MStokluska commented
@valerymo please update https://github.com/3scale/3scale-operator/blob/master/doc/development.md and double check if there's any other mentions of 1.20 as required. 
Also, please open midstream and openshift releases PRs - in case of questions reach out to me. Thanks!

2025-01-09 11:09 UTC, MStokluska commented on .circleci/config.yml
> +      - image: cimg/go:1.22
please rebase and switch images to: quay.io/3scale/operators-ci-images:v1.22

2025-01-13 09:55 UTC, valerymo commented on .circleci/config.yml
> +      - image: cimg/go:1.22
Done. Thank you

2025-01-13 11:48 UTC, valerymo commented
> @valerymo please update https://github.com/3scale/3scale-operator/blob/master/doc/development.md and double check if there's any other mentions of 1.20 as required. Also, please open midstream and openshift releases PRs - in case of questions reach out to me. Thanks!

@MStokluska  development.md - updated. No other places with go 1.20 found. Thank you for comment.

2025-01-13 14:03 UTC, MStokluska approved these changes

2025-01-13 14:04 UTC, MStokluska commented on Dockerfile
> +FROM golang:1.22.0 as builder
this needs to change @valerymo

2025-01-13 14:05 UTC, MStokluska requested changes
Please move docker base image from docker hub

2025-01-13 15:06 UTC, valerymo commented on Dockerfile
> +FROM golang:1.22.0 as builder
Thank you Michal. Changed to `mirror.gcr.io/library/golang:1.22.8` as discussed.

2025-01-13 15:06 UTC, valerymo commented
> Please move docker base image from docker hub

done. changed to `FROM mirror.gcr.io/library/golang:1.22.8 as builder` as discussed

2025-01-14 10:19 UTC, merged