Add configurable 'last' attribute in mapping rules
3scale/3scale-operator pull request #447
Opened 2020-08-06 10:20 UTC by miguelsorianod

Add the optional 'last' attribute in MappingRules for Products and Backends

2020-08-06 10:21 UTC, miguelsorianod commented on pkg/controller/product/mapping_rules.go
> +			"last":        strconv.FormatBool(lastAttribute),
An alternative would be only specifying the 'last' parameter to 3scale api when it's been set to a non-nil value in the CR

2020-08-24 15:41 UTC, eguzki requested changes

2020-08-24 17:44 UTC, miguelsorianod commented on pkg/controller/backend/3scale_reconciler.go
> +		if desiredLastAttribute != data.item.Last {
I think if `data.spec.Last` is `nil` and `data.item.Last` is `true` we should set it to false as the default value when `data.spec.last` is `nil` would be `false` when not defined.
To me that it reconciliates only when is defined with a non-nil value in the CRD is confusing. CRD should be authoritative.

2020-08-25 12:06 UTC, miguelsorianod commented on pkg/controller/product/mapping_rules.go
> +			"last":        strconv.FormatBool(lastAttribute),
Updated createNewMappingRules method to only send "last" parameter to the 3scale API when it is set to a non-nil value

2020-08-25 12:06 UTC, miguelsorianod commented on pkg/controller/backend/3scale_reconciler.go
> +			"last":        strconv.FormatBool(lastAttribute),
Updated createNewMappingRules method to only send "last" parameter to the 3scale API when it is set to a non-nil value in the CR

2020-08-26 15:04 UTC, eguzki commented
missing doc

2020-08-27 11:02 UTC, miguelsorianod commented
Added documentation

2020-08-27 13:11 UTC, eguzki approved these changes

2020-08-27 13:48 UTC, merged