Document update
3scale/3scale-operator pull request #455
Opened 2020-08-25 10:12 UTC by PoojaChandak

Observed a few grammatical changes. Suggesting the same.

2020-08-25 11:45 UTC, miguelsorianod requested changes
Hi,

Thanks for your contribution.

I've left some feedback about the changes

2020-08-25 11:45 UTC, miguelsorianod commented on doc/operator-backup-and-restore.md
> +a custom resource is provided.
I think this change would not be correct.

2020-08-25 11:45 UTC, miguelsorianod commented on doc/operator-backup-and-restore.md
> +   the content of APIManagerBackup and waiting until the `.status.completed` the field
I think this change would not be correct

2020-08-25 11:45 UTC, miguelsorianod commented on doc/operator-capabilities.md
> +* **NOTE 2**: `metricMethodRef` holds a reference to the existing metric or method map key name `system_name`. In the example, `hits`.
I think this change should be 'to an existing metric...' instead of 'to the existing metric...'

2020-08-25 11:45 UTC, miguelsorianod commented on doc/operator-capabilities.md
> +* **NOTE 2**: `metricMethodRef` holds a reference to the existing metric or method map key name `system_name`. In the example, `hits`.
I think this change should be 'to an existing metric...' instead of 'to the existing metric...'

2020-08-25 11:45 UTC, miguelsorianod commented on doc/operator-capabilities.md
> +Define the desired product application plan limits declaratively using the `applicationPlans.limits` list.
I think 'the' might not be needed here

2020-08-25 14:09 UTC, PoojaChandak commented
Review comments incorporated.

2020-08-25 15:22 UTC, miguelsorianod requested changes
Looks good to me.

Can you update the PR to be on top of current master?

Thanks!

2020-08-25 15:26 UTC, PoojaChandak commented
repository synced.

2020-08-25 15:29 UTC, miguelsorianod commented
Thanks @PoojaChandak !

2020-08-25 15:30 UTC, PoojaChandak commented
Happy to be able to contribute. :) Thanks.

2020-08-25 15:30 UTC, miguelsorianod commented
hmm wait, can you rebase on top of master instead of merging?
We want to keep a clean history

2020-08-25 15:36 UTC, PoojaChandak commented
I am using the browser editor of github to add these changes, unsure how to rebase from here. Could you help with that?

2020-08-26 15:09 UTC, eguzki commented
This can be helpful: https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a

2020-08-31 05:35 UTC, PoojaChandak commented
Followed https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a. Rebase completed. Thank you for your help. Kindly check now.

2020-08-31 08:59 UTC, miguelsorianod approved these changes

2020-08-31 09:00 UTC, miguelsorianod commented
Hi @PoojaChandak,

Looks good to me. Thanks for your work :+1:

2020-08-31 09:00 UTC, merged