Circleci trigger image build workflow
3scale/3scale-operator pull request #555
Opened 2020-12-18 18:55 UTC by eguzki

2021-01-08 13:23 UTC, miguelsorianod commented on Makefile
> +	CONTRjLLER_GEN_TMP_DIR=$$(mktemp -d) ;\
Introduced change with a typo

2021-01-08 13:26 UTC, miguelsorianod requested changes
Looks good.

Fix the error in the comment I left and rebase and all ok :+1:

2021-01-13 11:22 UTC, eguzki commented on Makefile
> +	CONTRjLLER_GEN_TMP_DIR=$$(mktemp -d) ;\
good catch!

2021-01-13 11:22 UTC, eguzki commented
Ready for review @miguelsorianod

2021-01-13 11:31 UTC, miguelsorianod approved these changes
:+1:

2021-01-13 12:08 UTC, merged