apicast loglevel
3scale/3scale-operator pull request #557
Opened 2020-12-22 18:28 UTC by eguzki

Adds configurability of `APICAST_LOG_LEVEL` in apicast production and apicast staging spec.

Includes reconciliation of env vars for apicast production and staging deploymentconfigs only for the specified env var `APICAST_LOG_LEVEL`. 

No need to implement upgrade procedure.

2021-01-08 13:39 UTC, miguelsorianod commented on pkg/3scale/amp/operator/apicast_reconciler.go
> +	// there is a better way to do this implemented in https://github.com/3scale/3scale-operator/pull/548
:+1: . Pending

2021-01-08 13:40 UTC, miguelsorianod requested changes
looks good.

I like the approach on the envvar reconciler :+1:

2021-01-13 17:42 UTC, eguzki commented on pkg/3scale/amp/operator/apicast_reconciler.go
> +	// there is a better way to do this implemented in https://github.com/3scale/3scale-operator/pull/548
Refactored using updates from #562

2021-01-13 17:42 UTC, eguzki commented
ready for review @miguelsorianod

2021-01-14 09:11 UTC, miguelsorianod approved these changes

2021-01-14 09:24 UTC, miguelsorianod requested changes
changing state to request changes due to this is for 2.10 branch

2021-01-14 09:28 UTC, eguzki commented
It has been decided to not include in 2.10. Only  to 2.11

2021-01-14 09:28 UTC, closed without merging