Stop using nightly images
3scale/3scale-operator pull request #636
Opened 2021-07-14 15:43 UTC by miguelsorianod

This PR performs the following changes:
* Stop referencing `nightly` tags for the 3scale components container images (system, zync, ...)
* Stop building nightly images in the nightly job. It is important to notice that although it removes the build of nightly images it still runs some tests nightly
* Rename the CSV displayName to `3scale (development latest)`
* Rename the devnightly sample to devlatest
* Update templates
* Update code-level defaults to use `latest`

2021-07-15 08:20 UTC, miguelsorianod commented
/retest

2021-07-16 11:13 UTC, miguelsorianod commented
/retest

2021-07-16 12:53 UTC, miguelsorianod commented
ready @eguzki

2021-07-19 10:48 UTC, eguzki requested changes
rebase the branch to the current master

2021-07-19 10:48 UTC, eguzki commented on .circleci/config.yml
> -      - build-push-3scale-images:
`build-push-3scale-images` is being used? It should be removed if not used

2021-07-19 10:55 UTC, eguzki commented
`images-build` workflow should also be removed.

2021-07-19 10:57 UTC, eguzki commented
`pkg/3scale/amp/manual-templates/amp/build.yml` is being used?

2021-07-19 11:01 UTC, miguelsorianod commented
Done

2021-07-19 11:48 UTC, eguzki approved these changes

2021-07-19 12:43 UTC, merged