change the makefile install to use create rather that apply
3scale/3scale-operator pull request #684
Opened 2021-11-03 14:06 UTC by austincunningham

# Issue
When running `make install` the apimanager crd fails to upload
```bash
make install
/home/austincunningham/repo-integr8ly/3scale-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/activedocs.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/apimanagerbackups.apps.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/apimanagerrestores.apps.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/backends.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/custompolicydefinitions.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/developeraccounts.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/developerusers.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/openapis.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/products.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/tenants.capabilities.3scale.net configured
The CustomResourceDefinition "apimanagers.apps.3scale.net" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
make: *** [Makefile:124: install] Error 1
```
This is due to `kubectl apply` it stores the entire spec as an annotation in the object as part of the apply

Change the makefile to use `kubeclt create` instead as this doesn't have the same issue

2021-11-03 14:18 UTC, eguzki commented
the `kubectl create` would fail the second time you execute or the first time when the crds already exists. Since, this is developer tool, how about adding a makefile dependency of the `install` target as the `uninstall` target?

```
install: uninstall manifests $(KUSTOMIZE)
```

2021-11-03 14:57 UTC, miguelsorianod commented
Can we do a "replace and if it fails create" instead, to avoid deleting the existing CRDs?

2021-11-04 08:18 UTC, austincunningham commented
@miguelsorianod 
Tested this behavior 
```bash
install: manifests $(KUSTOMIZE)
	$(KUSTOMIZE) build config/crd | $(KUBECTL) create -f - || $(KUSTOMIZE) build config/crd | $(KUBECTL) replace -f -
```
out looks ok on the first and second run
```bash
# first run
~ make install
/home/austincunningham/repo-integr8ly/3scale-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl create -f - || /home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl replace -f -
customresourcedefinition.apiextensions.k8s.io/activedocs.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/apimanagerbackups.apps.3scale.net created
customresourcedefinition.apiextensions.k8s.io/apimanagerrestores.apps.3scale.net created
customresourcedefinition.apiextensions.k8s.io/apimanagers.apps.3scale.net created
customresourcedefinition.apiextensions.k8s.io/backends.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/custompolicydefinitions.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/developeraccounts.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/developerusers.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/openapis.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/products.capabilities.3scale.net created
customresourcedefinition.apiextensions.k8s.io/tenants.capabilities.3scale.net created
# Second run
~ make install
/home/austincunningham/repo-integr8ly/3scale-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl create -f - || /home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl replace -f -
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "activedocs.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "apimanagerbackups.apps.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "apimanagerrestores.apps.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "apimanagers.apps.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "backends.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "custompolicydefinitions.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "developeraccounts.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "developerusers.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "openapis.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "products.capabilities.3scale.net" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "tenants.capabilities.3scale.net" already exists
customresourcedefinition.apiextensions.k8s.io/activedocs.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/apimanagerbackups.apps.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/apimanagerrestores.apps.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/apimanagers.apps.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/backends.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/custompolicydefinitions.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/developeraccounts.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/developerusers.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/openapis.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/products.capabilities.3scale.net replaced
customresourcedefinition.apiextensions.k8s.io/tenants.capabilities.3scale.net replaced
```

2021-11-04 08:42 UTC, eguzki approved these changes

2021-11-04 08:53 UTC, miguelsorianod approved these changes
Looks good to me :+1: . Thank you.

2021-11-04 08:54 UTC, miguelsorianod requested changes
Could you squash the commits please?

2021-11-04 09:16 UTC, austincunningham commented
@miguelsorianod commits squashed

2021-11-04 09:30 UTC, miguelsorianod approved these changes

2021-11-04 10:09 UTC, merged