disable replicas reconiliation when annotation is present
3scale/3scale-operator pull request #736
Opened 2022-04-14 07:42 UTC by MStokluska

This resolves the https://issues.redhat.com/browse/THREESCALE-8374

Verification
- deploy 3scale
- add annotation to the apiManager `manualHPA: 'true'`
- edit the replicas on the `backend-worker`, `backend-listener`, `apicast-production` and confirm that they are not being rolled back to what's in the apimanager
- edit the resources limits on the deployments of the above and confirm that they have been rolled back to initial values

2022-04-14 11:01 UTC, eguzki requested changes
You have only changed the mutators, which only applies when the objects exist in the cluster. 

If you create the APIManager withh replicas set to some number, the deploymentconfig replicas will be set to that number as well. Then changes in the replica fields will not be reconciled. I would also set initial replicas to 1 if the annotation exists.

It also makes me feel uneasy that only backend (listernet, worker) and apicast (prodcution) deployment mutators are being conditioned by the annotation. Why not all of them? I see two options to be consistent. 
* the annotation afffects to all replicas
* we have component specific annotation, for instance: `apps.3scale.net/apicast-replica-field: false`
wdyt?

2022-05-18 11:24 UTC, MStokluska commented
Hey @eguzki I think this is ready for a review again. I still have to test it locally but I think the general flow should make more sense now.

2022-05-30 11:21 UTC, den-rgb commented
/lgtm

2022-05-30 11:22 UTC, den-rgb commented
Looks good and code works as expected, pod count did not change until set to false.

2022-05-31 10:28 UTC, eguzki requested changes

2022-05-31 10:28 UTC, eguzki commented on pkg/reconcilers/deploymentconfig.go
> +func GetConfigMutators(annotations map[string]string, annotation string) []DCMutateFn {
The name is confusing

It relies on `GenericOpts()` while it would be less coupled if list of mutators is passed. to the method

2022-05-31 10:29 UTC, eguzki commented
missing doc  that should be [here](https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#APIManagerMetaData)

2022-06-01 11:14 UTC, MStokluska commented on pkg/3scale/amp/operator/apicast_reconciler_test.go
> +			if err := configv1.AddToScheme(s); err != nil {
This has been added due to an error when it's not present:
```
FAIL: TestApicastServicePortMutator (0.00s)
    /home/mstokluska/dev/3scale-operator/pkg/3scale/amp/operator/apicast_reconciler_test.go:749: no kind is registered for the type v1.ClusterVersion in scheme "pkg/runtime/scheme.go:101"
    --- FAIL: TestApicastServicePortMutator/annotationTrue
    ```

2022-06-01 11:16 UTC, MStokluska commented on pkg/3scale/amp/operator/backend_reconciler_test.go
> +	configv1 "github.com/openshift/api/config/v1"
Without it there's an error in the unit tests:
```
--- FAIL: TestAnnotationsBackendReconciler (0.00s)
    /home/mstokluska/dev/3scale-operator/pkg/3scale/amp/operator/backend_reconciler_test.go:193: no kind is registered for the type v1.ClusterVersion in scheme "pkg/runtime/scheme.go:101"
    ```

2022-06-01 11:21 UTC, MStokluska commented on pkg/3scale/amp/operator/backend_reconciler_test.go
> +	configv1 "github.com/openshift/api/config/v1"
would this be the cause of it? https://github.com/3scale/3scale-operator/pull/745/files#diff-371a262496d28a74b4d341686c1355b403141fabfd1c1019183978a2026f1c18

2022-06-01 21:00 UTC, merged