Adressing proxy promotion issues
3scale/3scale-operator pull request #773
Opened 2022-07-27 09:00 UTC by Patryk-Stefanski

# What 

Addressing issues raised in this [comment ](https://issues.redhat.com/browse/THREESCALE-7135)

# Verification 

1. Deploy 3scale-operator locally 

2.Create dummy smtp secret
```sh
kubectl apply -f - <<EOF
---
kind: Secret
apiVersion: v1
metadata: 
  name: s3-credentials
  namespace: 3scale-test
data: 
  AWS_ACCESS_KEY_ID: UkVQTEFDRV9NRQ==
  AWS_BUCKET: UkVQTEFDRV9NRQ==
  AWS_REGION: UkVQTEFDRV9NRQ==
  AWS_SECRET_ACCESS_KEY: UkVQTEFDRV9NRQ==
type: Opaque
EOF
```

3.Create apimanager resource
```sh
kubectl apply -f - <<EOF
---
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata: 
  name: apimanager-sample
  namespace: 3scale-test
spec: 
  system: 
    fileStorage: 
      simpleStorageService: 
        configurationSecretRef: 
          name: s3-credentials
  wildcardDomain: <cluster_domain>
EOF
```
cluster domain example : `apps.pstefans.uq32.s1.devshift.org`

4. Create Backend resource
```sh
kubectl apply -f - <<EOF
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: backend1-cr
  namespace: 3scale-test
spec:
  mappingRules:
    - httpMethod: GET
      increment: 1
      last: true
      metricMethodRef: hits
      pattern: /
  name: backend1
  privateBaseURL: 'https://api.example.com'
  systemName: backend1
EOF
```

5. Create product resources with the backend referenced
```sh
kubectl apply -f - <<EOF
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: product1-cr
  namespace: 3scale-test
spec:
  name: product1
  backendUsages:
    backend1:
      path: /
EOF
```

6. Create proxyconfigpromote resources  to promote product to staging.
```sh
kubectl apply -f - <<EOF
---
apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  name: product1-v1-staging
  namespace: 3scale-test
spec:
  productCRName: product1-cr
 production: true
EOF
```

7. In 3scale UI check that product1 configuration was promoted to staging and that the CR now correctly reflects the staging and production versions.

2022-07-27 09:21 UTC, eguzki commented
/ok-to-test

2022-07-28 09:56 UTC, eguzki commented
Can you fix indenting issues like https://github.com/3scale/3scale-operator/pull/773/files#diff-b7a85d834496ef811bc135bcf19a9cb43d407ed592225b17396bc8bcaaeff8cbR17? Not a big deal, but things like this are very weird

```
| **Field**                  | **json field**       | **Type** | **Info**                                                                                                                                                   | **Required** |
|----------------------------|----------------------|----------|------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|
```

2022-07-28 10:01 UTC, eguzki requested changes

2022-07-28 10:01 UTC, eguzki commented on controllers/capabilities/proxyconfigpromote_controller.go
> +			} else {
this "spaghetti code" is calling for a refactor :)

2022-07-28 10:01 UTC, eguzki commented on controllers/capabilities/proxyconfigpromote_controller.go
> +			} else {
not to be done in this PR, though

2022-07-28 10:11 UTC, eguzki commented
verification steps have passed

2022-07-28 10:29 UTC, Patryk-Stefanski commented on doc/proxyConfigPromote-reference.md
> +#### Provider Account Reference
good spot, added it in. Thanks.

2022-07-29 14:48 UTC, eguzki approved these changes

2022-07-29 14:49 UTC, merged