[WIP] THREESCALE-8535 initial bump
3scale/3scale-operator pull request #785
Opened 2022-10-03 13:26 UTC by MStokluska

What's done so far
- bumped Go to 1.17
- bumped k8s apis to 0.23.5
- refactor some files to match the new requirements

2022-10-11 08:25 UTC, MStokluska commented
@eguzki I would appreciate it if you could have a look at it, main areas I'm concerned with are:
- apimanager reconciler watcher update
- grafana bump to v4 and removal on the spec.name field (yet to do on cluster upgrade verification)

2022-10-11 09:02 UTC, MStokluska commented
/test test-e2e
/test test-unit

2022-10-11 11:01 UTC, eguzki requested changes
Awesome work :medal_military: 

Left some comments

This graphana major version bump needs to be analyzed. What happens when upgrading from earlier version and 3scale has grafana dashboards deployed? The grafana operator needs to be upgraded, before the 3scale operator I guess. Needs to be documented.

2022-10-11 11:49 UTC, MStokluska commented on doc/prometheusrules/apicast.yaml
> +        == 0
Hey, this was done in order to get the prometheus rules tests to pass. I am not sure as of yet why is this required to get the tests pass (what changes the expected format) but will dig deeper.

2022-10-11 12:02 UTC, MStokluska commented
> update Makefile's `go-get-tool` method to use `go install` instead of `go get`. Maybe rename the method to `go-bin-install` ??

@eguzki this change actually causes the issue around kustomize
```
go install: sigs.k8s.io/kustomize/kustomize/v3@v3.5.4 (in sigs.k8s.io/kustomize/kustomize/v3@v3.5.4):
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
make: *** [Makefile:102: /go/src/github.com/3scale/3scale-operator/bin/kustomize] Error 1

Exited with code exit status 2
```
Will look into this.

2022-10-11 13:12 UTC, MStokluska commented
/test test-e2e

2022-10-11 13:15 UTC, MStokluska commented
E2E fails due to it being tested on ocp 4.6, which does not have policy/v1 but policy/v1beta1. I suggest bumping ocp testing clusters to at least 4.8

2022-10-11 14:01 UTC, MStokluska commented
/test test-e2e

2022-10-11 14:08 UTC, eguzki commented
I suggest to bump also kustomize and controller-gen, 

kustomize v4.5.7
controller-gen v0.9.2

Aligned with the apicast operator [PR](https://github.com/3scale/apicast-operator/pull/180)

2022-10-24 15:23 UTC, eguzki submitted a review, later dismissed

2022-10-24 15:26 UTC, eguzki commented
LGTM, before merging, update `/doc/development.md` accordingly

2022-10-24 17:03 UTC, eguzki requested changes
update /doc/development.md accordingly

2022-10-25 09:44 UTC, eguzki approved these changes

2022-10-25 10:45 UTC, merged