THREESCALE-9001 / Added Zync Routes Resync Function
3scale/3scale-operator pull request #846
Opened 2023-07-26 14:10 UTC by den-rgb

2023-08-01 08:20 UTC, Patryk-Stefanski reviewed
Verified that a root got recreated after being deleted, and left one small comment.

2023-08-01 08:20 UTC, Patryk-Stefanski commented on pkg/helper/podHelper.go
> +// ExecuteRemoteCommand exec command on specific pod and wait the command's output.
Is this comment needed?

2023-08-01 10:26 UTC, Patryk-Stefanski commented
/lgtm

2023-08-02 08:20 UTC, thomasmaas commented
/ok-to-test

2023-08-17 10:25 UTC, eguzki requested changes
Overall, I have serious doubts whether this is the right approach or not. Not saying it is wrongly implemetned, just saying we are taking some decisions that are controversial. 

1. The operator is acquiring knowledge about the expected routes. This something that belongs to 3scale internals. Although it is true that the `status` reconciler reads the basic installation's expected routes, this implementation takes one step further.
2. The implementation is part of the 3scale reconciler, blocking 3scale deployment when doing the task. The operator installation pattern is about creating resources and reading state to take actions. It should never be blocked executing one process in a pod or waiting of some resource to be ready. 
3. The process can be run multiple times in parallel. Note there are multiple event sources that trigger apimanager controller reconciliation. For instance, when any of the deploymentconfigs change status, the reconcile loop is executed.
4. Have you considered a different approach? For instance, one shot CRD (like ProxyConfigPromote CRD) that will trigger one (and only one) process to recreate the routes. So, when the user misses some routes, or restores a deleted namespace, an instance can be created to run re-sync. I understand that it is much better experience if the operator detects automatically missing routes and self-heals installation. Just rising discussion as the implementation adds complexity

2023-08-17 10:25 UTC, eguzki commented on pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
> +func (r *BaseAPIManagerLogicReconciler) getAccountUrls() ([]string, []string, error){
There is a library where we have this implemented: https://github.com/3scale/3scale-porta-go-client

2023-08-17 10:25 UTC, eguzki commented on pkg/helper/podHelper.go
> +	kubeClient, restConfig, err := getClient()
about this client, is not available from the controller manager?

2023-08-17 10:25 UTC, eguzki commented on pkg/helper/podHelper.go
> +	err = exec.Stream(remotecommand.StreamOptions{
This is blocking, right? Meaning that the controller's runtime will be waiting for the process in the pod to be finished.

2023-08-28 14:30 UTC, austincunningham commented
closing this as won't do

2023-08-28 14:30 UTC, closed without merging